apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: debug-snyk
  title: debug-snyk
  description: Template for debugging
  tags:
    - debug
spec:
  owner: MatthewThomas
  type: debug
  steps:
    - id: template
      name: Snyk import projects
      action: snyk:import-projects
      input:
        repoOwner: Ma11thewThomas
        repoName: matthew-thomas-backstage-plugins
        repoBranchName: main
        snykOrganizationId: your-org-id
        snykIntegrationId: your-integration-id
